name: ravifi
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  brick_core: ^1.4.0
  brick_offline_first_with_supabase: ^1.0.0
  brick_sqlite: ^3.1.0
  brick_supabase: ^1.4.1+1
  duration_picker: ^1.2.0
  flutter_slidable: ^4.0.0
  get: ^4.6.6
  intl: ^0.20.2
  sqflite: ^2.3.0
  sqflite_common: ^2.5.4+6
  sqflite_common_ffi: ^2.3.4+4
  supabase_flutter: ^2.8.3
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  brick_offline_first_with_supabase_build: ^1.0.0
  build_runner: ^2.4.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
