name: ravifi
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  brick_core: ^1.4.0
  brick_offline_first: ^3.4.0
  brick_offline_first_with_supabase: ^1.0.0
  brick_sqlite: ^3.1.0
  brick_supabase: ^1.4.1+1
  duration_picker: ^1.2.0
  fl_chart: ^0.70.2
  flutter_slidable: ^4.0.0
  get: ^4.6.6
  image: ^4.5.2
  image_picker: ^1.1.2
  intl: ^0.20.2
  path_provider: ^2.1.5
  sqflite: ^2.3.0
  sqflite_common: ^2.5.4+6
  sqflite_common_ffi: ^2.3.4+4
  supabase_flutter: ^2.8.3
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  brick_offline_first_with_supabase_build: ^1.0.0
  build_runner: ^2.4.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: ChakraPetch
      fonts:
        - asset: fonts/ChakraPetch-Bold.ttf
          weight: 700
        - asset: fonts/ChakraPetch-Light.ttf
          weight: 300
        - asset: fonts/ChakraPetch-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/ChakraPetch-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: fonts/ChakraPetch-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: fonts/ChakraPetch-LightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/ChakraPetch-Regular.ttf
          weight: 400
        - asset: fonts/ChakraPetch-Italic.ttf
          style: italic
          weight: 400
        - asset: fonts/ChakraPetch-Medium.ttf
          weight: 500
        - asset: fonts/ChakraPetch-SemiBold.ttf
          weight: 600